* Note on patch matrix
  The astute reader will notice a number of cryptic references to a
  so-called 'patch matrix'.  This allows the program to be internally
  re-wired like patching a modular synth.  Patch index denotes an
  output & each patch-matrix-enabled input may choose one and only one
  source from the patch matrix.
** Patch matrix Cheatsheet:
0. Effect Bus
1. ADC 1
2. ADC 2
3. ADC 3
4. ADC 4
5. grain1 output
6. grain2 output
7. grain1 echoTap pitchtrack oscillator
8. grain2 echoTap pitchtrack oscillator
9. grain1 echoTap envelope
10. grain2 echoTap envelope
11. LFO
12. noise burst
13. static_CV1
14. static_CV2
* CV Params
** Source_cv1
   Choose source for CV out 1 from patch matrix
** Source_cv2
   Choose source for CV out 2 from patch matrix
** Source_cv3
   Choose source for CV out 3 from patch matrix
** Source_cv4
   Choose source for CV out 4 from patch matrix
* ADC mix params
  ADCs 1&2 are hard-wired to dedicated mixer channel:
** fader_i<n>
   Stereo fader from ADC i to DACS 1&2
** pan_i<n>
   Stereo pan from ADC i between DACS 1&2
** effect_i<n>
   Send from ADC i to effect bus
** aux0_i<n>
   Fader from ADC i to DAC3
** aux1_i<n>
   Fader from ADC i to DAC4
   Mixer channels 3 & 4 have an additional control:
** source_i<n>
   Choose mixer channel input from patch matrix
* Grain Mix params
** source_g<m> [1:14]
   Choose grain input from patch matrix
** fader_g<m>
   Stereo fader from grain i to DACS 1&2
** pan_g<m>
   Stereo pan from grain i between DACS 1&2
** effect_g<m>p
   Send from grain i to effect bus
** aux0_g<m>
   Fader from grain i to DAC3
** aux1_g<m>
   Fader from grain i to DAC4
** phase_g<m>
   phase of grain i (+ve or -ve)
** lpf_g<m>
   Cutoff frequency (in Hz) for grain output (low-pass filter)
* Grain Modulation Params
** FM_source_g<m>
   Choose a signal from patch matrix to modulate scrubPitch of grain.
   If scrubbing disabled, FM becomes PM (modulating read position
   relative to echotap.
** FM_level_g<m>
   Set depth of modulation induced by FM_source
** AM_source
   Choose a signal from patch matrix to modulate amplitude of grain
   output.
** AM_level_g<m>
   Pan between modulated and unmodulated grain output.
* Grain Scrub params
** scrubEnable_g<m>
   enable scrubbing behaviour for this grain (pitch control
   independent of echo speed).
** scrubPitch_g<m> f8x8[0:7]
   speed of scrubber read tap in subsamples (1/256 sample) - bees
   displays 1.000 at speed = 1 sample/sample
** scrubLength_g<m> i24
   length of scrubber read distance from echo readhead before cross-fading.
   This is expressed as a ratio to the scrubberFadeLength
** scrubPitchDetection_g<m>
   When this is enabled, scrublength 'snaps' to an even multiple of
   grain input signal.  Zero crossing pitch detection with adaptive
   filter.
* Grain Echo params
** echoFadeLength_g<m>
   length for scrubber crossfades.  Again expressed as a ratio to echomax-echomin
** echoTime_g<m>
   allows bees to force read head to a point, e.g:
   - set echo time for simple echo fx
   - trigger one-shot sample for pre-recorded audio
** echoSpeed_g<m>
   For canonical realtime FX like this guy should be 1, so the
   echo-tap stays in sync with write head. When a sample is loaded
   into the fifo this guy replays the sample.  See echoEdgeBehaviour
   for playback modes.  If you're feeling crazy unglue the echo tap
   from writing head while write head runs by setting this value != 1
** echoEdgeBehaviour_g<m>
   set this to 0 or 1 to control does echo-tap head stall, or wrap at
   echo boundary respectively?  Also possible to retrigger one-shot samples by
   resending 0.
** echoMin_g<m>
   echo boundary nearest to write-head
** echoMax_g<m>
   echo boundary furthest from write-head
** writeEnable_g<m>
   Choose between constantly writing new data into echotap or simply
   re-playing already-recorded audio in the underlying buffer.
* Grain Pitch & Amplitude Analysis / Tracking
** envAttack_g<m>
   Attack of the envelope detector - bit rough atm but smaller number
   -> slower attack
** trackingEnv_g<m>
   Multiply PitchTracking Oscillator by grain envelope befre sending
   it to patch matrix.
** trackingPitch_g<m>
   Frequency Offset factor for pitchTracking oscillator/synth
* Grains Utilities
** LFO_speed
   Speed of LFO (smaller number = slower oscillation down to very slow
   oscillations.  LFO signal is output to patch matrix.
** LFO_shape
   Blend between a triangular LFO shape (0) and sinusoid shape (max)
** noiseBurst
   Trigger a noise burst impulse into patch matrix
** noiseBurstDecay
   How quickly does noise burst impulse decay (small number = long burst)
** static_CV1
   Set a DC value from BEES on static_CV1 slot in patch matrix
** static_CV2
   Set a DC value from BEES on static_CV2 slot in patch matrix
* What is a grain?
so a grain consists a buffer, a write head running at 1x, an 'echoTap'
& a 'scrubTap'.

    The write head is the same as the one in lines - I set the
    underlying buffer to be very long.  The echoTap is like a lines
    read head but it can run at non-integer speeds, it's time coord is
    relative to the write head (wrapping round the underlying buffer
    is hidden) but playback speed is relative to the underlying buffer
    (though think there's a subtle bug in this respect with current
    release).  The scrubTap is kind of similar to an echoTap but it's
    time coord is relative to the echoTap, and it's time coord is much
    finer grained than the echoTap.

* Bugggzzzz
  Please send bug reports / patches to sasquatch@rickvenn.com or
  github.com/rick-monster/aleph I will be happy to hear from you
  whether something is wrong with the module, you want to send me beer
  or music you have made using this software or just to say hello.  I
  might even *fix* any bugs that crop up...
