This is the text specification for a new bees serial protocol allowing
communication between aleph and a host over usb serial.

WARNING this document is now somewhat out of date.  Since the protocol
will be in a state of flux while I build serial support into my host
app, I defer updating this document until there is some stability.
Until then what is here is probably mostly correct but incomplete. For
anyone fluent in lisp check the file
utils/serial-com-proto/test-harness.lisp - that should be considered
the reference implementation for now...

sorry!

rick

Here's how to access serial terminal from lisp on linux:

http://ryepup.unwashedmeme.com/blog/2009/09/28/talking-usb-serial-to-my-arduino-from-lisp-sbcl-on-linux/

* bees sends debug message
  framed[SERIAL_DEBUG, "some debug message"]
* serial operator pings host
  framed[OP_SERIAL,addr_hi,addr_lo,val_hi,val_lo]
* host requests all bees inputs:
  framed[DUMP_INS]
* bees replies with delimited list of namestrings :
  framed[INS_DUMP, "in_one,in_two..."] (not necessarily comma-delimited)

* host requests list of all DSP params:
  framed[DUMP_PARAMS]
* bees replies with delimited list of namestrings:
  framed[PARAMS_DUMP,"param_one,param_two..."]

* host triggers any dsp input:
  framed[TRIGGER_PARAM, addr_hi,addr_lo,val_hi,val_lo]
* host triggers any bees input:
  framed[TRIGGER_IN,addr_hi,addr_lo,val_hi,val_lo]

* host queries some bees input by index:
  framed[QUERY_IN,addr_hi,addr_lo]
* bees responds with current value on bees input:
  framed[IN_VAL, addr_hi,addr_lo,val_hi,val_lo]

* host queries some DSP param by index:
  framed[QUERY_PARAM,addr_hi,addr_lo]
* bees responds with current value of DSP value:
  framed[PARAM_VAL,addr_hi,addr_lo,val_hi,val_lo]
