 
// autogenerated from param_gen.scd 

#include <string.h>
#include "module.h"
#include "params.h" 

void fill_param_desc(void) {
  strcpy(gModuleData->paramDesc[eParam_delay0].label, "delay0");
  gModuleData->paramDesc[eParam_delay0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_delay0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_delay0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_delay0].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_loop0].label, "loop0");
  gModuleData->paramDesc[eParam_loop0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_loop0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_loop0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_loop0].radix = PARAM_SECONDS_RADIX;

  // rate multiplier
  strcpy(gModuleData->paramDesc[eParam_rMul0].label, "rMul0");
  gModuleData->paramDesc[eParam_rMul0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rMul0].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rMul0].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rMul0].radix = 32;

  // rate divider
  strcpy(gModuleData->paramDesc[eParam_rDiv0].label, "rDiv0");
  gModuleData->paramDesc[eParam_rDiv0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rDiv0].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rDiv0].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rDiv0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_write0].label, "write0");
  gModuleData->paramDesc[eParam_write0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_write0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_write0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_write0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pre0].label, "pre0");
  gModuleData->paramDesc[eParam_pre0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_pre0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pre0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_pre0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pos_write0].label, "pos_write0");
  gModuleData->paramDesc[eParam_pos_write0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_write0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_write0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_write0].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_pos_read0].label, "pos_read0");
  gModuleData->paramDesc[eParam_pos_read0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_read0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_read0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_read0].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_run_write0].label, "run_write0");
  gModuleData->paramDesc[eParam_run_write0].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_write0].min = 0;
  gModuleData->paramDesc[eParam_run_write0].max = 1; 
  gModuleData->paramDesc[eParam_run_write0].radix = 2; 

  strcpy(gModuleData->paramDesc[eParam_run_read0].label, "run_read0");
  gModuleData->paramDesc[eParam_run_read0].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_read0].min = 0;
  gModuleData->paramDesc[eParam_run_read0].max = 1; 
  gModuleData->paramDesc[eParam_run_read0].radix = 2; 

  strcpy(gModuleData->paramDesc[eParam_delay1].label, "delay1");
  gModuleData->paramDesc[eParam_delay1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_delay1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_delay1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_delay1].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_loop1].label, "loop1");
  gModuleData->paramDesc[eParam_loop1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_loop1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_loop1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_loop1].radix = PARAM_SECONDS_RADIX;

  /// FIXME
  //// ????
  strcpy(gModuleData->paramDesc[eParam_rMul1].label, "rMul1");
  gModuleData->paramDesc[eParam_rMul1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rMul1].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rMul1].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rMul1].radix = 32; 

  strcpy(gModuleData->paramDesc[eParam_rDiv1].label, "rDiv1");
  gModuleData->paramDesc[eParam_rDiv1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rDiv1].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rDiv1].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rDiv1].radix = 32; 

  strcpy(gModuleData->paramDesc[eParam_write1].label, "write1");
  gModuleData->paramDesc[eParam_write1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_write1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_write1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_write1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pre1].label, "pre1");
  gModuleData->paramDesc[eParam_pre1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_pre1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pre1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_pre1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pos_write1].label, "pos_write1");
  gModuleData->paramDesc[eParam_pos_write1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_write1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_write1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_write1].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_pos_read1].label, "pos_read1");
  gModuleData->paramDesc[eParam_pos_read1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_read1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_read1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_read1].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_run_write1].label, "run_write1");
  gModuleData->paramDesc[eParam_run_write1].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_write1].min = 0;
  gModuleData->paramDesc[eParam_run_write1].max = 1;
  gModuleData->paramDesc[eParam_run_write1].radix = 2;

  strcpy(gModuleData->paramDesc[eParam_run_read1].label, "run_read1");
  gModuleData->paramDesc[eParam_run_read1].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_read1].min = 0;
  gModuleData->paramDesc[eParam_run_read1].max = 1;
  gModuleData->paramDesc[eParam_run_read1].radix = 2;

  strcpy(gModuleData->paramDesc[eParam_freq0].label, "cut0");
  gModuleData->paramDesc[eParam_freq0].type = eParamTypeSvfFreq; 
  gModuleData->paramDesc[eParam_freq0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_freq0].max = PARAM_CUT_MAX;
  gModuleData->paramDesc[eParam_freq0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_rq0].label, "rq0");
  gModuleData->paramDesc[eParam_rq0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rq0].min = PARAM_RQ_MIN;
  gModuleData->paramDesc[eParam_rq0].max = PARAM_RQ_MAX;
  gModuleData->paramDesc[eParam_rq0].radix = 2;
  
  strcpy(gModuleData->paramDesc[eParam_low0].label, "low0");
  gModuleData->paramDesc[eParam_low0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_low0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_low0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_low0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_high0].label, "high0");
  gModuleData->paramDesc[eParam_high0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_high0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_high0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_high0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_band0].label, "band0");
  gModuleData->paramDesc[eParam_band0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_band0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_band0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_band0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_notch0].label, "notch0");
  gModuleData->paramDesc[eParam_notch0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_notch0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_notch0].max = 0x00010000;
  gModuleData->paramDesc[eParam_notch0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_fwet0].label, "fwet0");
  gModuleData->paramDesc[eParam_fwet0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fwet0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fwet0].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fwet0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_fdry0].label, "fdry0");
  gModuleData->paramDesc[eParam_fdry0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fdry0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fdry0].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fdry0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_freq1].label, "cut1");
  gModuleData->paramDesc[eParam_freq1].type = eParamTypeSvfFreq; 
  gModuleData->paramDesc[eParam_freq1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_freq1].max = PARAM_CUT_MAX; 
  gModuleData->paramDesc[eParam_freq1].radix = 1;

  ///// FIXME
  strcpy(gModuleData->paramDesc[eParam_rq1].label, "rq1");
  gModuleData->paramDesc[eParam_rq1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rq1].min = PARAM_RQ_MIN;
  gModuleData->paramDesc[eParam_rq1].max = PARAM_RQ_MAX; 
  gModuleData->paramDesc[eParam_rq1].radix = 2;
 
  strcpy(gModuleData->paramDesc[eParam_low1].label, "low1");
  gModuleData->paramDesc[eParam_low1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_low1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_low1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_low1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_high1].label, "high1");
  gModuleData->paramDesc[eParam_high1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_high1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_high1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_high1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_band1].label, "band1");
  gModuleData->paramDesc[eParam_band1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_band1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_band1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_band1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_notch1].label, "notch1");
  gModuleData->paramDesc[eParam_notch1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_notch1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_notch1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_notch1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_fwet1].label, "fwet1");
  gModuleData->paramDesc[eParam_fwet1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fwet1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fwet1].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fwet1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_fdry1].label, "fdry1");
  gModuleData->paramDesc[eParam_fdry1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fdry1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fdry1].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fdry1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_del0].label, "adc0_del0");
  gModuleData->paramDesc[eParam_adc0_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_del1].label, "adc0_del1");
  gModuleData->paramDesc[eParam_adc0_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_del0].label, "adc1_del0");
  gModuleData->paramDesc[eParam_adc1_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_del1].label, "adc1_del1");
  gModuleData->paramDesc[eParam_adc1_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_del0].label, "adc2_del0");
  gModuleData->paramDesc[eParam_adc2_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_del1].label, "adc2_del1");
  gModuleData->paramDesc[eParam_adc2_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_del0].label, "adc3_del0");
  gModuleData->paramDesc[eParam_adc3_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_del1].label, "adc3_del1");
  gModuleData->paramDesc[eParam_adc3_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_del0].label, "del0_del0");
  gModuleData->paramDesc[eParam_del0_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_del1].label, "del0_del1");
  gModuleData->paramDesc[eParam_del0_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_del0].label, "del1_del0");
  gModuleData->paramDesc[eParam_del1_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_del1].label, "del1_del1");
  gModuleData->paramDesc[eParam_del1_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac0].label, "adc0_dac0");
  gModuleData->paramDesc[eParam_adc0_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac1].label, "adc0_dac1");
  gModuleData->paramDesc[eParam_adc0_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac2].label, "adc0_dac2");
  gModuleData->paramDesc[eParam_adc0_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac3].label, "adc0_dac3");
  gModuleData->paramDesc[eParam_adc0_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac0].label, "adc1_dac0");
  gModuleData->paramDesc[eParam_adc1_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac1].label, "adc1_dac1");
  gModuleData->paramDesc[eParam_adc1_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac2].label, "adc1_dac2");
  gModuleData->paramDesc[eParam_adc1_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac3].label, "adc1_dac3");
  gModuleData->paramDesc[eParam_adc1_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac0].label, "adc2_dac0");
  gModuleData->paramDesc[eParam_adc2_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac1].label, "adc2_dac1");
  gModuleData->paramDesc[eParam_adc2_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac2].label, "adc2_dac2");
  gModuleData->paramDesc[eParam_adc2_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac3].label, "adc2_dac3");
  gModuleData->paramDesc[eParam_adc2_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac0].label, "adc3_dac0");
  gModuleData->paramDesc[eParam_adc3_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac1].label, "adc3_dac1");
  gModuleData->paramDesc[eParam_adc3_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac2].label, "adc3_dac2");
  gModuleData->paramDesc[eParam_adc3_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac3].label, "adc3_dac3");
  gModuleData->paramDesc[eParam_adc3_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac0].label, "del0_dac0");
  gModuleData->paramDesc[eParam_del0_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac1].label, "del0_dac1");
  gModuleData->paramDesc[eParam_del0_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac2].label, "del0_dac2");
  gModuleData->paramDesc[eParam_del0_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac3].label, "del0_dac3");
  gModuleData->paramDesc[eParam_del0_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac0].label, "del1_dac0");
  gModuleData->paramDesc[eParam_del1_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac1].label, "del1_dac1");
  gModuleData->paramDesc[eParam_del1_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac2].label, "del1_dac2");
  gModuleData->paramDesc[eParam_del1_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac3].label, "del1_dac3");
  gModuleData->paramDesc[eParam_del1_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac3].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_del1_dac3].radix = 1;
}

// EOF
