 
// autogenerated from param_gen.scd 

#include <string.h>
#include "module.h"
#include "params.h" 

void fill_param_desc(void) {
  strcpy(gModuleData->paramDesc[eParam_delay0].label, "delay0");
  gModuleData->paramDesc[eParam_delay0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_delay0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_delay0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_delay0].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_loop0].label, "loop0");
  gModuleData->paramDesc[eParam_loop0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_loop0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_loop0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_loop0].radix = PARAM_SECONDS_RADIX;

  // rate multiplier
  strcpy(gModuleData->paramDesc[eParam_rMul0].label, "rMul0");
  gModuleData->paramDesc[eParam_rMul0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rMul0].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rMul0].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rMul0].radix = 32;

  // rate divider
  strcpy(gModuleData->paramDesc[eParam_rDiv0].label, "rDiv0");
  gModuleData->paramDesc[eParam_rDiv0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rDiv0].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rDiv0].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rDiv0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_write0].label, "write0");
  gModuleData->paramDesc[eParam_write0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_write0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_write0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_write0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pre0].label, "pre0");
  gModuleData->paramDesc[eParam_pre0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_pre0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pre0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_pre0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pos_write0].label, "pos_write0");
  gModuleData->paramDesc[eParam_pos_write0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_write0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_write0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_write0].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_pos_read0].label, "pos_read0");
  gModuleData->paramDesc[eParam_pos_read0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_read0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_read0].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_read0].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_run_write0].label, "run_write0");
  gModuleData->paramDesc[eParam_run_write0].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_write0].min = 0;
  gModuleData->paramDesc[eParam_run_write0].max = 1; 
  gModuleData->paramDesc[eParam_run_write0].radix = 2; 

  strcpy(gModuleData->paramDesc[eParam_run_read0].label, "run_read0");
  gModuleData->paramDesc[eParam_run_read0].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_read0].min = 0;
  gModuleData->paramDesc[eParam_run_read0].max = 1; 
  gModuleData->paramDesc[eParam_run_read0].radix = 2; 

  strcpy(gModuleData->paramDesc[eParam_delay1].label, "delay1");
  gModuleData->paramDesc[eParam_delay1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_delay1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_delay1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_delay1].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_loop1].label, "loop1");
  gModuleData->paramDesc[eParam_loop1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_loop1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_loop1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_loop1].radix = PARAM_SECONDS_RADIX;

  /// FIXME
  //// ????
  strcpy(gModuleData->paramDesc[eParam_rMul1].label, "rMul1");
  gModuleData->paramDesc[eParam_rMul1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rMul1].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rMul1].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rMul1].radix = 32; 

  strcpy(gModuleData->paramDesc[eParam_rDiv1].label, "rDiv1");
  gModuleData->paramDesc[eParam_rDiv1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rDiv1].min = 0x00010000; 
  gModuleData->paramDesc[eParam_rDiv1].max = 0x00080000; 
  gModuleData->paramDesc[eParam_rDiv1].radix = 32; 

  strcpy(gModuleData->paramDesc[eParam_write1].label, "write1");
  gModuleData->paramDesc[eParam_write1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_write1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_write1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_write1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pre1].label, "pre1");
  gModuleData->paramDesc[eParam_pre1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_pre1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pre1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_pre1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_pos_write1].label, "pos_write1");
  gModuleData->paramDesc[eParam_pos_write1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_write1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_write1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_write1].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_pos_read1].label, "pos_read1");
  gModuleData->paramDesc[eParam_pos_read1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_pos_read1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_pos_read1].max = PARAM_SECONDS_MAX; 
  gModuleData->paramDesc[eParam_pos_read1].radix = PARAM_SECONDS_RADIX;

  strcpy(gModuleData->paramDesc[eParam_run_write1].label, "run_write1");
  gModuleData->paramDesc[eParam_run_write1].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_write1].min = 0;
  gModuleData->paramDesc[eParam_run_write1].max = 1;
  gModuleData->paramDesc[eParam_run_write1].radix = 2;

  strcpy(gModuleData->paramDesc[eParam_run_read1].label, "run_read1");
  gModuleData->paramDesc[eParam_run_read1].type = eParamTypeBool; 
  gModuleData->paramDesc[eParam_run_read1].min = 0;
  gModuleData->paramDesc[eParam_run_read1].max = 1;
  gModuleData->paramDesc[eParam_run_read1].radix = 2;

  strcpy(gModuleData->paramDesc[eParam_freq0].label, "cut0");
  gModuleData->paramDesc[eParam_freq0].type = eParamTypeSvfFreq; 
  gModuleData->paramDesc[eParam_freq0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_freq0].max = PARAM_CUT_MAX;
  gModuleData->paramDesc[eParam_freq0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_rq0].label, "rq0");
  gModuleData->paramDesc[eParam_rq0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rq0].min = PARAM_RQ_MIN;
  gModuleData->paramDesc[eParam_rq0].max = PARAM_RQ_MAX;
  gModuleData->paramDesc[eParam_rq0].radix = 2;
  
  strcpy(gModuleData->paramDesc[eParam_low0].label, "low0");
  gModuleData->paramDesc[eParam_low0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_low0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_low0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_low0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_high0].label, "high0");
  gModuleData->paramDesc[eParam_high0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_high0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_high0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_high0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_band0].label, "band0");
  gModuleData->paramDesc[eParam_band0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_band0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_band0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_band0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_notch0].label, "notch0");
  gModuleData->paramDesc[eParam_notch0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_notch0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_notch0].max = 0x00010000;
  gModuleData->paramDesc[eParam_notch0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_fwet0].label, "fwet0");
  gModuleData->paramDesc[eParam_fwet0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fwet0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fwet0].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fwet0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_fdry0].label, "fdry0");
  gModuleData->paramDesc[eParam_fdry0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fdry0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fdry0].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fdry0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_freq1].label, "cut1");
  gModuleData->paramDesc[eParam_freq1].type = eParamTypeSvfFreq; 
  gModuleData->paramDesc[eParam_freq1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_freq1].max = PARAM_CUT_MAX; 
  gModuleData->paramDesc[eParam_freq1].radix = 1;

  ///// FIXME
  strcpy(gModuleData->paramDesc[eParam_rq1].label, "rq1");
  gModuleData->paramDesc[eParam_rq1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_rq1].min = PARAM_RQ_MIN;
  gModuleData->paramDesc[eParam_rq1].max = PARAM_RQ_MAX; 
  gModuleData->paramDesc[eParam_rq1].radix = 2;
 
  strcpy(gModuleData->paramDesc[eParam_low1].label, "low1");
  gModuleData->paramDesc[eParam_low1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_low1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_low1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_low1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_high1].label, "high1");
  gModuleData->paramDesc[eParam_high1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_high1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_high1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_high1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_band1].label, "band1");
  gModuleData->paramDesc[eParam_band1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_band1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_band1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_band1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_notch1].label, "notch1");
  gModuleData->paramDesc[eParam_notch1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_notch1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_notch1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_notch1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_fwet1].label, "fwet1");
  gModuleData->paramDesc[eParam_fwet1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fwet1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fwet1].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fwet1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_fdry1].label, "fdry1");
  gModuleData->paramDesc[eParam_fdry1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_fdry1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_fdry1].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_fdry1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_del0].label, "adc0_del0");
  gModuleData->paramDesc[eParam_adc0_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_del1].label, "adc0_del1");
  gModuleData->paramDesc[eParam_adc0_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_del0].label, "adc1_del0");
  gModuleData->paramDesc[eParam_adc1_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_del1].label, "adc1_del1");
  gModuleData->paramDesc[eParam_adc1_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_del0].label, "adc2_del0");
  gModuleData->paramDesc[eParam_adc2_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_del1].label, "adc2_del1");
  gModuleData->paramDesc[eParam_adc2_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_del0].label, "adc3_del0");
  gModuleData->paramDesc[eParam_adc3_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_del1].label, "adc3_del1");
  gModuleData->paramDesc[eParam_adc3_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_del0].label, "del0_del0");
  gModuleData->paramDesc[eParam_del0_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_del1].label, "del0_del1");
  gModuleData->paramDesc[eParam_del0_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_del0].label, "del1_del0");
  gModuleData->paramDesc[eParam_del1_del0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_del0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_del0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_del0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_del1].label, "del1_del1");
  gModuleData->paramDesc[eParam_del1_del1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_del1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_del1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_del1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac0].label, "adc0_dac0");
  gModuleData->paramDesc[eParam_adc0_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac1].label, "adc0_dac1");
  gModuleData->paramDesc[eParam_adc0_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac2].label, "adc0_dac2");
  gModuleData->paramDesc[eParam_adc0_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc0_dac3].label, "adc0_dac3");
  gModuleData->paramDesc[eParam_adc0_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc0_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc0_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc0_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac0].label, "adc1_dac0");
  gModuleData->paramDesc[eParam_adc1_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac1].label, "adc1_dac1");
  gModuleData->paramDesc[eParam_adc1_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac2].label, "adc1_dac2");
  gModuleData->paramDesc[eParam_adc1_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc1_dac3].label, "adc1_dac3");
  gModuleData->paramDesc[eParam_adc1_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc1_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc1_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc1_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac0].label, "adc2_dac0");
  gModuleData->paramDesc[eParam_adc2_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac1].label, "adc2_dac1");
  gModuleData->paramDesc[eParam_adc2_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac2].label, "adc2_dac2");
  gModuleData->paramDesc[eParam_adc2_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc2_dac3].label, "adc2_dac3");
  gModuleData->paramDesc[eParam_adc2_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc2_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc2_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc2_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac0].label, "adc3_dac0");
  gModuleData->paramDesc[eParam_adc3_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac1].label, "adc3_dac1");
  gModuleData->paramDesc[eParam_adc3_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac2].label, "adc3_dac2");
  gModuleData->paramDesc[eParam_adc3_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_adc3_dac3].label, "adc3_dac3");
  gModuleData->paramDesc[eParam_adc3_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_adc3_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_adc3_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_adc3_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac0].label, "del0_dac0");
  gModuleData->paramDesc[eParam_del0_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac1].label, "del0_dac1");
  gModuleData->paramDesc[eParam_del0_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac2].label, "del0_dac2");
  gModuleData->paramDesc[eParam_del0_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del0_dac3].label, "del0_dac3");
  gModuleData->paramDesc[eParam_del0_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del0_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del0_dac3].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del0_dac3].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac0].label, "del1_dac0");
  gModuleData->paramDesc[eParam_del1_dac0].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac0].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_dac0].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac1].label, "del1_dac1");
  gModuleData->paramDesc[eParam_del1_dac1].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac1].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_dac1].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac2].label, "del1_dac2");
  gModuleData->paramDesc[eParam_del1_dac2].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac2].max = FR32_MAX;
  gModuleData->paramDesc[eParam_del1_dac2].radix = 1;

  strcpy(gModuleData->paramDesc[eParam_del1_dac3].label, "del1_dac3");
  gModuleData->paramDesc[eParam_del1_dac3].type = eParamTypeAmp; 
  gModuleData->paramDesc[eParam_del1_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_del1_dac3].max = FR32_MAX; 
  gModuleData->paramDesc[eParam_del1_dac3].radix = 1;

  // filter slew

  strcpy(gModuleData->paramDesc[eParamCut0Slew].label, "cut0Slew");
  gModuleData->paramDesc[eParamCut0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamCut0Slew].min = 0;
  gModuleData->paramDesc[eParamCut0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamCut0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamRq0Slew].label, "rq0Slew");
  gModuleData->paramDesc[eParamRq0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamRq0Slew].min = 0;
  gModuleData->paramDesc[eParamRq0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamRq0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamLow0Slew].label, "low0Slew");
  gModuleData->paramDesc[eParamLow0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamLow0Slew].min = 0;
  gModuleData->paramDesc[eParamLow0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamLow0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamHigh0Slew].label, "high0Slew");
  gModuleData->paramDesc[eParamHigh0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamHigh0Slew].min = 0;
  gModuleData->paramDesc[eParamHigh0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamHigh0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamBand0Slew].label, "band0Slew");
  gModuleData->paramDesc[eParamBand0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamBand0Slew].min = 0;
  gModuleData->paramDesc[eParamBand0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamBand0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamNotch0Slew].label, "notch0Slew");
  gModuleData->paramDesc[eParamNotch0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamNotch0Slew].min = 0;
  gModuleData->paramDesc[eParamNotch0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamNotch0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamDry0Slew].label, "dry0Slew");
  gModuleData->paramDesc[eParamDry0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamDry0Slew].min = 0;
  gModuleData->paramDesc[eParamDry0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamDry0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamWet0Slew].label, "wet0Slew");
  gModuleData->paramDesc[eParamWet0Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamWet0Slew].min = 0;
  gModuleData->paramDesc[eParamWet0Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamWet0Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamCut1Slew].label, "cut1Slew");
  gModuleData->paramDesc[eParamCut1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamCut1Slew].min = 0;
  gModuleData->paramDesc[eParamCut1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamCut1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamRq1Slew].label, "rq1Slew");
  gModuleData->paramDesc[eParamRq1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamRq1Slew].min = 0;
  gModuleData->paramDesc[eParamRq1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamRq1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamLow1Slew].label, "low1Slew");
  gModuleData->paramDesc[eParamLow1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamLow1Slew].min = 0;
  gModuleData->paramDesc[eParamLow1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamLow1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamHigh1Slew].label, "high1Slew");
  gModuleData->paramDesc[eParamHigh1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamHigh1Slew].min = 0;
  gModuleData->paramDesc[eParamHigh1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamHigh1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamBand1Slew].label, "band1Slew");
  gModuleData->paramDesc[eParamBand1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamBand1Slew].min = 0;
  gModuleData->paramDesc[eParamBand1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamBand1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamNotch1Slew].label, "notch1Slew");
  gModuleData->paramDesc[eParamNotch1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamNotch1Slew].min = 0;
  gModuleData->paramDesc[eParamNotch1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamNotch1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamDry1Slew].label, "dry1Slew");
  gModuleData->paramDesc[eParamDry1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamDry1Slew].min = 0;
  gModuleData->paramDesc[eParamDry1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamDry1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamWet1Slew].label, "wet1Slew");
  gModuleData->paramDesc[eParamWet1Slew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamWet1Slew].min = 0;
  gModuleData->paramDesc[eParamWet1Slew].max = FR32_MAX;
  gModuleData->paramDesc[eParamWet1Slew].radix = 32;

  strcpy(gModuleData->paramDesc[eParamMixSlew].label, "mixSlew");
  gModuleData->paramDesc[eParamMixSlew].type = eParamTypeIntegrator;
  gModuleData->paramDesc[eParamMixSlew].min = 0;
  gModuleData->paramDesc[eParamMixSlew].max = FR32_MAX;
  gModuleData->paramDesc[eParamMixSlew].radix = 32;

  /////

  strcpy(gModuleData->paramDesc[eParam_cvVal0].label, "cv0");
  gModuleData->paramDesc[eParam_cvVal0].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_cvVal0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvVal0].max = PARAM_DAC_MAX;
  gModuleData->paramDesc[eParam_cvVal0].radix = PARAM_DAC_RADIX;

  strcpy(gModuleData->paramDesc[eParam_cvVal1].label, "cv1");
  gModuleData->paramDesc[eParam_cvVal1].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_cvVal1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvVal1].max = PARAM_DAC_MAX;
  gModuleData->paramDesc[eParam_cvVal1].radix = PARAM_DAC_RADIX;

  strcpy(gModuleData->paramDesc[eParam_cvVal2].label, "cv2");
  gModuleData->paramDesc[eParam_cvVal2].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_cvVal2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvVal2].max = PARAM_DAC_MAX;
  gModuleData->paramDesc[eParam_cvVal2].radix = PARAM_DAC_RADIX;

  strcpy(gModuleData->paramDesc[eParam_cvVal3].label, "cv3");
  gModuleData->paramDesc[eParam_cvVal3].type = eParamTypeFix; 
  gModuleData->paramDesc[eParam_cvVal3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvVal3].max = PARAM_DAC_MAX;
  gModuleData->paramDesc[eParam_cvVal3].radix = PARAM_DAC_RADIX;

  strcpy(gModuleData->paramDesc[eParam_cvSlew0].label, "cvSlew0");
  gModuleData->paramDesc[eParam_cvSlew0].type = eParamTypeIntegrator; 
  gModuleData->paramDesc[eParam_cvSlew0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvSlew0].max = 0x7fffffff;
  gModuleData->paramDesc[eParam_cvSlew0].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_cvSlew1].label, "cvSlew1");
  gModuleData->paramDesc[eParam_cvSlew1].type = eParamTypeIntegrator; 
  gModuleData->paramDesc[eParam_cvSlew1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvSlew1].max = 0x7fffffff;
  gModuleData->paramDesc[eParam_cvSlew1].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_cvSlew2].label, "cvSlew2");
  gModuleData->paramDesc[eParam_cvSlew2].type = eParamTypeIntegrator; 
  gModuleData->paramDesc[eParam_cvSlew2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvSlew2].max = 0x7fffffff; 
  gModuleData->paramDesc[eParam_cvSlew2].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_cvSlew3].label, "cvSlew3");
  gModuleData->paramDesc[eParam_cvSlew3].type = eParamTypeIntegrator; 
  gModuleData->paramDesc[eParam_cvSlew3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvSlew3].max = 0x7fffffff;
  gModuleData->paramDesc[eParam_cvSlew3].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_cvSlew2].label, "cvSlew2");
  gModuleData->paramDesc[eParam_cvSlew2].type = eParamTypeIntegrator; 
  gModuleData->paramDesc[eParam_cvSlew2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvSlew2].max = 0x7fffffff; 
  gModuleData->paramDesc[eParam_cvSlew2].radix = 32;

  strcpy(gModuleData->paramDesc[eParam_cvSlew3].label, "cvSlew3");
  gModuleData->paramDesc[eParam_cvSlew3].type = eParamTypeIntegrator; 
  gModuleData->paramDesc[eParam_cvSlew3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_cvSlew3].max = 0x7fffffff;
  gModuleData->paramDesc[eParam_cvSlew3].radix = 32;

  strcpy(gModuleData->paramDesc[eParamFade0].label, "fade0");
  gModuleData->paramDesc[eParamFade0].type = eParamTypeFix;
  gModuleData->paramDesc[eParamFade0].min = PARAM_FADE_MIN;
  gModuleData->paramDesc[eParamFade0].max = PARAM_FADE_MAX;
  gModuleData->paramDesc[eParamFade0].radix = PARAM_FADE_RADIX;

  strcpy(gModuleData->paramDesc[eParamFade1].label, "fade1");
  gModuleData->paramDesc[eParamFade1].type = eParamTypeFix;
  gModuleData->paramDesc[eParamFade1].min = PARAM_FADE_MIN;
  gModuleData->paramDesc[eParamFade1].max = PARAM_FADE_MAX;
  gModuleData->paramDesc[eParamFade1].radix = PARAM_FADE_RADIX;

}

// EOF
