#!/usr/bin/env python3
"""generate dsp_block/filter_bp_alpha_tab.c — base-width filter coefficients.

the mx44 base-width filter parameterizes its 1-pole HP and 1-pole LP corners
in semitones above a 1 Hz root (f = 2^(st/12) Hz). alphas are baked here so
the module needs no divides or transcendentals at run time.

HP alpha is solved numerically against the realized digital response, so the
-3 dB corner lands on the nominal frequency across the whole base range. the
naive analog-prototype formula it replaces drifts to 1.8x by 5 kHz and past
Nyquist by 10 kHz.

LP alpha uses the impulse-invariant 1 - e^(-wT). that is exact to ~2 kHz and,
unlike a -3 dB-matched design, keeps climbing monotonically toward unity above
Nyquist — which is the transparent regime a low-pass wants at the open end.

both endpoints are forced to FR32_MAX so a fully open filter is bit
transparent: hp[0] passes to within 23 LSB of 2^31, lp[LP_ST_MAX] is exact.

usage:
    python3 utils/param_scaling/gen_bp_alpha_tab.py > dsp_block/filter_bp_alpha_tab.c
"""

import cmath
import math
import sys

SR = 48000
FR32_MAX = 0x7FFFFFFF

# semitone axis, root 1 Hz. HP tops out at 8192 Hz (st 156); the LP axis runs
# to 65536 Hz (st 192) so that base + width always reaches the open end.
HP_ST_MAX = 156
LP_ST_MAX = 192

MINUS_3DB = 10.0 ** (-3.0 / 20.0)


def st_to_hz(st):
    return 2.0 ** (st / 12.0)


def hp_mag(alpha, f):
    """|H| of y[n] = a*(y[n-1] + x[n] - x[n-1])."""
    z = cmath.exp(1j * 2.0 * math.pi * f / SR)
    return abs(alpha * (1.0 - 1.0 / z) / (1.0 - alpha / z))


def hp_alpha_for(fc):
    """bisect for the alpha whose realized -3 dB corner is fc."""
    lo, hi = 1e-12, 1.0
    for _ in range(200):
        mid = (lo + hi) / 2.0
        if hp_mag(mid, fc) < MINUS_3DB:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2.0


def lp_alpha_for(fc):
    return 1.0 - math.exp(-2.0 * math.pi * fc / SR)


def to_fract32(x):
    v = int(round(x * FR32_MAX))
    return max(0, min(FR32_MAX, v))


def emit_table(out, name, values):
    out.write("const fract32 %s[%s] = {\n" % (name, len(values)))
    for i in range(0, len(values), 6):
        row = values[i:i + 6]
        out.write("    " + " ".join("0x%08x," % v for v in row) + "\n")
    out.write("};\n")


def main():
    hp = [to_fract32(hp_alpha_for(st_to_hz(st))) for st in range(HP_ST_MAX + 1)]
    lp = [to_fract32(lp_alpha_for(st_to_hz(st))) for st in range(LP_ST_MAX + 1)]

    hp[0] = FR32_MAX
    lp[LP_ST_MAX] = FR32_MAX

    # guard entry so interpolation at the top index can read tab[i + 1]
    hp.append(hp[-1])
    lp.append(lp[-1])

    if any(hp[i] < hp[i + 1] for i in range(len(hp) - 1)):
        raise SystemExit("hp table is not monotonically decreasing")
    if any(lp[i] > lp[i + 1] for i in range(len(lp) - 1)):
        raise SystemExit("lp table is not monotonically increasing")

    out = sys.stdout
    out.write("/* filter_bp_alpha_tab.c\n")
    out.write(" * aleph dsp_block\n")
    out.write(" *\n")
    out.write(" * GENERATED by utils/param_scaling/gen_bp_alpha_tab.py — do not edit.\n")
    out.write(" */\n\n")
    out.write('#include "filter_bp_alpha_tab.h"\n\n')
    emit_table(out, "filterBpAlphaHpTab", hp)
    out.write("\n")
    emit_table(out, "filterBpAlphaLpTab", lp)


if __name__ == "__main__":
    main()
