#ifndef _CONFIG_H_
#define _CONFIG_H_

/*
///// UASRT1 in spi mode for OLED
#define OLED_USART_SPI                 (&AVR32_USART1)
// clock is PA07
#define OLED_USART_SPI_SCK_PIN         AVR32_USART1_CLK_0_PIN
#define OLED_USART_SPI_SCK_FUNCTION    AVR32_USART1_CLK_0_FUNCTION
// rx is PA05
#define OLED_USART_SPI_MISO_PIN        AVR32_USART1_RXD_0_0_PIN
#define OLED_USART_SPI_MISO_FUNCTION   AVR32_USART1_RXD_0_0_FUNCTION
// tx is PA06 
#define OLED_USART_SPI_MOSI_PIN        AVR32_USART1_TXD_0_0_PIN
#define OLED_USART_SPI_MOSI_FUNCTION   AVR32_USART1_TXD_0_0_FUNCTION
// rts (chip select) is PA08
#define OLED_USART_SPI_NSS_PIN         AVR32_USART1_RTS_0_0_PIN
#define OLED_USART_SPI_NSS_FUNCTION    AVR32_USART1_RTS_0_0_FUNCTION
// PA09 in GPIO for OLED command/data register select
#define OLED_REGISTER_PIN AVR32_PIN_PA09
*/

// weird shit with the clock with EVK, i wonder if RS232 driver is interfering, 
// trying USART2 instead...

#  define OLED_USART_SPI                 (&AVR32_USART2)
#  define OLED_USART_SPI_SCK_PIN         AVR32_USART2_CLK_0_PIN
#  define OLED_USART_SPI_SCK_FUNCTION    AVR32_USART2_CLK_0_FUNCTION
#  define OLED_USART_SPI_MISO_PIN        AVR32_USART2_RXD_0_0_PIN
#  define OLED_USART_SPI_MISO_FUNCTION   AVR32_USART2_RXD_0_0_FUNCTION
#  define OLED_USART_SPI_MOSI_PIN        AVR32_USART2_TXD_0_0_PIN
#  define OLED_USART_SPI_MOSI_FUNCTION   AVR32_USART2_TXD_0_0_FUNCTION
#  define OLED_USART_SPI_NSS_PIN         AVR32_USART2_RTS_0_0_PIN
#  define OLED_USART_SPI_NSS_FUNCTION    AVR32_USART2_RTS_0_0_FUNCTION
// PA09 in GPIO for OLED command/data register select
#define OLED_REGISTER_PIN AVR32_PIN_PA09


// that works, going back to USART1... wow, just doesn't work (on EVK at least)
/*
#  define OLED_USART_SPI                 (&AVR32_USART2)
#  define OLED_USART_SPI_SCK_PIN         AVR32_USART1_CLK_0_PIN
#  define OLED_USART_SPI_SCK_FUNCTION    AVR32_USART1_CLK_0_FUNCTION
#  define OLED_USART_SPI_MISO_PIN        AVR32_USART1_RXD_0_0_PIN
#  define OLED_USART_SPI_MISO_FUNCTION   AVR32_USART1_RXD_0_0_FUNCTION
#  define OLED_USART_SPI_MOSI_PIN        AVR32_USART1_TXD_0_0_PIN
#  define OLED_USART_SPI_MOSI_FUNCTION   AVR32_USART1_TXD_0_0_FUNCTION
#  define OLED_USART_SPI_NSS_PIN         AVR32_USART1_RTS_0_0_PIN
#  define OLED_USART_SPI_NSS_FUNCTION    AVR32_USART1_RTS_0_0_FUNCTION
*/
#endif // header guard
