 
// autogenerated from param_gen.scd 

#include <string.h>
#include "module.h"
#include "params.h" 

void fill_param_desc(void) {
  strcpy(gModuleData->paramDesc[eParam_dac0].label, "dac0");
  strcpy(gModuleData->paramDesc[eParam_dac0].unit, "");
  gModuleData->paramDesc[eParam_dac0].type = PARAM_TYPE_FRACT; 
  gModuleData->paramDesc[eParam_dac0].min = 0x00000000; 
  gModuleData->paramDesc[eParam_dac0].max = 0xffff; // 16 bits?

  strcpy(gModuleData->paramDesc[eParam_dac1].label, "dac1");
  strcpy(gModuleData->paramDesc[eParam_dac1].unit, "");
  gModuleData->paramDesc[eParam_dac1].type = PARAM_TYPE_FRACT; 
  gModuleData->paramDesc[eParam_dac1].min = 0x00000000; 
  gModuleData->paramDesc[eParam_dac1].max = 0xffff; // 16 bits?

  strcpy(gModuleData->paramDesc[eParam_dac2].label, "dac2");
  strcpy(gModuleData->paramDesc[eParam_dac2].unit, "");
  gModuleData->paramDesc[eParam_dac2].type = PARAM_TYPE_FRACT; 
  gModuleData->paramDesc[eParam_dac2].min = 0x00000000; 
  gModuleData->paramDesc[eParam_dac2].max = 0xffff; // 16 bits?

  strcpy(gModuleData->paramDesc[eParam_dac3].label, "dac3");
  strcpy(gModuleData->paramDesc[eParam_dac3].unit, "");
  gModuleData->paramDesc[eParam_dac3].type = PARAM_TYPE_FRACT; 
  gModuleData->paramDesc[eParam_dac3].min = 0x00000000; 
  gModuleData->paramDesc[eParam_dac3].max = 0xffff; // 16 bits?

}

// EOF
