/* filter_bp_alpha_tab.h
 * aleph dsp_block
 *
 * 1-pole HP / LP coefficients for the base-width bandpass, indexed by
 * semitone above a 1 Hz root (f = 2^(st/12) Hz).
 *
 * cutoffs are controlled on this log axis rather than in Hz so that a fixed
 * width keeps the band a constant number of octaves wide as base sweeps, and
 * so that the endpoints reach exact identity coefficients: st 0 leaves the HP
 * fully open, LP_ST_MAX leaves the LP fully open. tables are generated by
 * utils/param_scaling/gen_bp_alpha_tab.py.
 */

#ifndef _ALEPH_DSP_BLOCK_FILTER_BP_ALPHA_TAB_H_
#define _ALEPH_DSP_BLOCK_FILTER_BP_ALPHA_TAB_H_

#include "fix.h"
#include "fract_math.h"
#include "types.h"

/* highest semitone in each table (1 Hz root): 8192 Hz and 65536 Hz */
#define FILTER_BP_ALPHA_HP_ST_MAX 156
#define FILTER_BP_ALPHA_LP_ST_MAX 192

/* semitone index in fix16 (integer semitones in the high 16 bits) */
#define FILTER_BP_ALPHA_HP_ST_MAX_FIX (FILTER_BP_ALPHA_HP_ST_MAX << 16)
#define FILTER_BP_ALPHA_LP_ST_MAX_FIX (FILTER_BP_ALPHA_LP_ST_MAX << 16)

/* each has one guard entry past ST_MAX so lookup can read tab[i + 1] */
extern const fract32 filterBpAlphaHpTab[FILTER_BP_ALPHA_HP_ST_MAX + 2];
extern const fract32 filterBpAlphaLpTab[FILTER_BP_ALPHA_LP_ST_MAX + 2];

static inline fract32 filter_bp_alpha_lookup(const fract32 *tab, fract32 stFix,
					     s32 stMaxFix) {
  s32 idx;
  fract32 frac;
  fract32 a;
  fract32 b;

  if(stFix < 0) {
    stFix = 0;
  } else if(stFix > stMaxFix) {
    stFix = stMaxFix;
  }

  idx = stFix >> 16;
  frac = (stFix & 0xffff) << 15; /* 16.16 fraction -> fract32 */
  a = tab[idx];
  b = tab[idx + 1];

  /* a + frac * (b - a); the difference between adjacent semitones is small
     enough that sub_fr1x32 cannot saturate. */
  return add_fr1x32(a, mult_fr1x32x32(frac, sub_fr1x32(b, a)));
}

/* stFix is fix16 semitones above 1 Hz */
static inline fract32 filter_bp_alpha_hp(fract32 stFix) {
  return filter_bp_alpha_lookup(filterBpAlphaHpTab, stFix,
				FILTER_BP_ALPHA_HP_ST_MAX_FIX);
}

static inline fract32 filter_bp_alpha_lp(fract32 stFix) {
  return filter_bp_alpha_lookup(filterBpAlphaLpTab, stFix,
				FILTER_BP_ALPHA_LP_ST_MAX_FIX);
}

#endif
